version: 0.2

# BuildSpec for Combined Build (API + Batch)
# This file builds both API and Batch processor containers in a single build

env:
  variables:
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo "========================================="
      - echo "Building Both API and Batch Containers"
      - echo "========================================="
      - echo "Build started on $(date)"
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $API_ECR_REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
      - echo "API Repository - $API_ECR_REPOSITORY_URI"
      - echo "Batch Repository - $BATCH_ECR_REPOSITORY_URI"
      - echo "Image tag - $IMAGE_TAG"
      - echo "Build number - $CODEBUILD_BUILD_NUMBER"
      
  build:
    commands:
      - echo "========================================="
      - echo "Building API Container"
      - echo "========================================="
      - cd backend
      - docker build -t $API_ECR_REPOSITORY_URI:latest -f Dockerfile .
      - docker tag $API_ECR_REPOSITORY_URI:latest $API_ECR_REPOSITORY_URI:$IMAGE_TAG
      - docker tag $API_ECR_REPOSITORY_URI:latest $API_ECR_REPOSITORY_URI:build-$CODEBUILD_BUILD_NUMBER
      - echo "API container built successfully"
      - echo ""
      - echo "========================================="
      - echo "Building Batch Container"
      - echo "========================================="
      - docker build -t $BATCH_ECR_REPOSITORY_URI:latest -f Dockerfile.batch .
      - docker tag $BATCH_ECR_REPOSITORY_URI:latest $BATCH_ECR_REPOSITORY_URI:$IMAGE_TAG
      - docker tag $BATCH_ECR_REPOSITORY_URI:latest $BATCH_ECR_REPOSITORY_URI:build-$CODEBUILD_BUILD_NUMBER
      - echo "Batch container built successfully"
      
  post_build:
    commands:
      - echo "========================================="
      - echo "Pushing API Images"
      - echo "========================================="
      - docker push $API_ECR_REPOSITORY_URI:latest
      - docker push $API_ECR_REPOSITORY_URI:$IMAGE_TAG
      - docker push $API_ECR_REPOSITORY_URI:build-$CODEBUILD_BUILD_NUMBER
      - echo "API images pushed successfully"
      - echo ""
      - echo "========================================="
      - echo "Pushing Batch Images"
      - echo "========================================="
      - docker push $BATCH_ECR_REPOSITORY_URI:latest
      - docker push $BATCH_ECR_REPOSITORY_URI:$IMAGE_TAG
      - docker push $BATCH_ECR_REPOSITORY_URI:build-$CODEBUILD_BUILD_NUMBER
      - echo "Batch images pushed successfully"
      - echo ""
      - echo "========================================="
      - echo "Build Complete!"
      - echo "========================================="
      - echo "API Repository - $API_ECR_REPOSITORY_URI"
      - echo "Batch Repository - $BATCH_ECR_REPOSITORY_URI"
      - echo "Tags - latest, $IMAGE_TAG, build-$CODEBUILD_BUILD_NUMBER"
      - echo "Build completed on $(date)"
      - echo "========================================="

cache:
  paths:
    - '/root/.cache/**/*'
    - '/var/lib/docker/**/*'
